/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ConquestInterface extends Interface {
  functions: {
    MAX_REWARD_AMOUNT: TypedFunctionDescription<{ encode([]: []): string }>;

    TIME_BETWEEN_CONQUESTS: TypedFunctionDescription<{
      encode([]: []): string;
    }>;

    conquestEntryAddress: TypedFunctionDescription<{ encode([]: []): string }>;

    conquestEntryID: TypedFunctionDescription<{ encode([]: []): string }>;

    conquestsEntered: TypedFunctionDescription<{
      encode([]: [string]): string;
    }>;

    getOwner: TypedFunctionDescription<{ encode([]: []): string }>;

    isActiveConquest: TypedFunctionDescription<{
      encode([]: [string]): string;
    }>;

    nextConquestTime: TypedFunctionDescription<{
      encode([]: [string]): string;
    }>;

    skyweaverAssets: TypedFunctionDescription<{ encode([]: []): string }>;

    transferOwnership: TypedFunctionDescription<{
      encode([_newOwner]: [string]): string;
    }>;

    onERC1155Received: TypedFunctionDescription<{
      encode([_operator, _from, _id, _amount, _data]: [
        string,
        string,
        BigNumberish,
        BigNumberish,
        Arrayish
      ]): string;
    }>;

    onERC1155BatchReceived: TypedFunctionDescription<{
      encode([, _from, _ids, _amounts]: [
        string,
        string,
        BigNumberish[],
        BigNumberish[],
        Arrayish
      ]): string;
    }>;

    exitConquest: TypedFunctionDescription<{
      encode([_user, _ids, _amounts]: [
        string,
        BigNumberish[],
        BigNumberish[]
      ]): string;
    }>;

    supportsInterface: TypedFunctionDescription<{
      encode([interfaceID]: [Arrayish]): string;
    }>;
  };

  events: {
    ConquestEntered: TypedEventDescription<{
      encodeTopics([user, nConquests]: [null, null]): string[];
    }>;

    OwnershipTransferred: TypedEventDescription<{
      encodeTopics([previousOwner, newOwner]: [
        string | null,
        string | null
      ]): string[];
    }>;
  };
}

export class Conquest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Conquest;
  attach(addressOrName: string): Conquest;
  deployed(): Promise<Conquest>;

  on(event: EventFilter | string, listener: Listener): Conquest;
  once(event: EventFilter | string, listener: Listener): Conquest;
  addListener(eventName: EventFilter | string, listener: Listener): Conquest;
  removeAllListeners(eventName: EventFilter | string): Conquest;
  removeListener(eventName: any, listener: Listener): Conquest;

  interface: ConquestInterface;

  functions: {
    MAX_REWARD_AMOUNT(): Promise<BigNumber>;

    TIME_BETWEEN_CONQUESTS(): Promise<BigNumber>;

    conquestEntryAddress(): Promise<string>;

    conquestEntryID(): Promise<BigNumber>;

    conquestsEntered(arg0: string): Promise<BigNumber>;

    getOwner(): Promise<string>;

    isActiveConquest(arg0: string): Promise<boolean>;

    nextConquestTime(arg0: string): Promise<BigNumber>;

    skyweaverAssets(): Promise<string>;

    transferOwnership(
      _newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    onERC1155Received(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _amount: BigNumberish,
      _data: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    onERC1155BatchReceived(
      arg0: string,
      _from: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    exitConquest(
      _user: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    supportsInterface(interfaceID: Arrayish): Promise<boolean>;
  };

  MAX_REWARD_AMOUNT(): Promise<BigNumber>;

  TIME_BETWEEN_CONQUESTS(): Promise<BigNumber>;

  conquestEntryAddress(): Promise<string>;

  conquestEntryID(): Promise<BigNumber>;

  conquestsEntered(arg0: string): Promise<BigNumber>;

  getOwner(): Promise<string>;

  isActiveConquest(arg0: string): Promise<boolean>;

  nextConquestTime(arg0: string): Promise<BigNumber>;

  skyweaverAssets(): Promise<string>;

  transferOwnership(
    _newOwner: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  onERC1155Received(
    _operator: string,
    _from: string,
    _id: BigNumberish,
    _amount: BigNumberish,
    _data: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  onERC1155BatchReceived(
    arg0: string,
    _from: string,
    _ids: BigNumberish[],
    _amounts: BigNumberish[],
    arg4: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  exitConquest(
    _user: string,
    _ids: BigNumberish[],
    _amounts: BigNumberish[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  supportsInterface(interfaceID: Arrayish): Promise<boolean>;

  filters: {
    ConquestEntered(user: null, nConquests: null): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimate: {
    MAX_REWARD_AMOUNT(): Promise<BigNumber>;

    TIME_BETWEEN_CONQUESTS(): Promise<BigNumber>;

    conquestEntryAddress(): Promise<BigNumber>;

    conquestEntryID(): Promise<BigNumber>;

    conquestsEntered(arg0: string): Promise<BigNumber>;

    getOwner(): Promise<BigNumber>;

    isActiveConquest(arg0: string): Promise<BigNumber>;

    nextConquestTime(arg0: string): Promise<BigNumber>;

    skyweaverAssets(): Promise<BigNumber>;

    transferOwnership(_newOwner: string): Promise<BigNumber>;

    onERC1155Received(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _amount: BigNumberish,
      _data: Arrayish
    ): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: string,
      _from: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: Arrayish
    ): Promise<BigNumber>;

    exitConquest(
      _user: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[]
    ): Promise<BigNumber>;

    supportsInterface(interfaceID: Arrayish): Promise<BigNumber>;
  };
}
