/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ConquestInterface extends Interface {
  functions: {
    assignOwnership: TypedFunctionDescription<{
      encode([_address, _tier]: [string, BigNumberish]): string;
    }>;

    conquestEntryID: TypedFunctionDescription<{ encode([]: []): string }>;

    conquestsEntered: TypedFunctionDescription<{
      encode([]: [string]): string;
    }>;

    exitConquest: TypedFunctionDescription<{
      encode([_user, _silverIds, _goldIds]: [
        string,
        BigNumberish[],
        BigNumberish[]
      ]): string;
    }>;

    getOwnerTier: TypedFunctionDescription<{
      encode([_owner]: [string]): string;
    }>;

    goldCardFactory: TypedFunctionDescription<{ encode([]: []): string }>;

    isActiveConquest: TypedFunctionDescription<{
      encode([]: [string]): string;
    }>;

    nextConquestTime: TypedFunctionDescription<{
      encode([]: [string]): string;
    }>;

    onERC1155BatchReceived: TypedFunctionDescription<{
      encode([, _from, _ids, _amounts]: [
        string,
        string,
        BigNumberish[],
        BigNumberish[],
        Arrayish
      ]): string;
    }>;

    onERC1155Received: TypedFunctionDescription<{
      encode([_operator, _from, _id, _amount, _data]: [
        string,
        string,
        BigNumberish,
        BigNumberish,
        Arrayish
      ]): string;
    }>;

    silverCardFactory: TypedFunctionDescription<{ encode([]: []): string }>;

    skyweaverAssets: TypedFunctionDescription<{ encode([]: []): string }>;

    supportsInterface: TypedFunctionDescription<{
      encode([interfaceID]: [Arrayish]): string;
    }>;
  };

  events: {
    ConquestEntered: TypedEventDescription<{
      encodeTopics([user, nConquests]: [null, null]): string[];
    }>;

    OwnershipGranted: TypedEventDescription<{
      encodeTopics([owner, previousTier, newTier]: [
        string | null,
        BigNumberish | null,
        BigNumberish | null
      ]): string[];
    }>;
  };
}

export class Conquest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Conquest;
  attach(addressOrName: string): Conquest;
  deployed(): Promise<Conquest>;

  on(event: EventFilter | string, listener: Listener): Conquest;
  once(event: EventFilter | string, listener: Listener): Conquest;
  addListener(eventName: EventFilter | string, listener: Listener): Conquest;
  removeAllListeners(eventName: EventFilter | string): Conquest;
  removeListener(eventName: any, listener: Listener): Conquest;

  interface: ConquestInterface;

  functions: {
    assignOwnership(
      _address: string,
      _tier: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    conquestEntryID(): Promise<BigNumber>;

    conquestsEntered(arg0: string): Promise<BigNumber>;

    exitConquest(
      _user: string,
      _silverIds: BigNumberish[],
      _goldIds: BigNumberish[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getOwnerTier(_owner: string): Promise<BigNumber>;

    goldCardFactory(): Promise<string>;

    isActiveConquest(arg0: string): Promise<boolean>;

    nextConquestTime(arg0: string): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: string,
      _from: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    onERC1155Received(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _amount: BigNumberish,
      _data: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    silverCardFactory(): Promise<string>;

    skyweaverAssets(): Promise<string>;

    supportsInterface(interfaceID: Arrayish): Promise<boolean>;
  };

  assignOwnership(
    _address: string,
    _tier: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  conquestEntryID(): Promise<BigNumber>;

  conquestsEntered(arg0: string): Promise<BigNumber>;

  exitConquest(
    _user: string,
    _silverIds: BigNumberish[],
    _goldIds: BigNumberish[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  getOwnerTier(_owner: string): Promise<BigNumber>;

  goldCardFactory(): Promise<string>;

  isActiveConquest(arg0: string): Promise<boolean>;

  nextConquestTime(arg0: string): Promise<BigNumber>;

  onERC1155BatchReceived(
    arg0: string,
    _from: string,
    _ids: BigNumberish[],
    _amounts: BigNumberish[],
    arg4: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  onERC1155Received(
    _operator: string,
    _from: string,
    _id: BigNumberish,
    _amount: BigNumberish,
    _data: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  silverCardFactory(): Promise<string>;

  skyweaverAssets(): Promise<string>;

  supportsInterface(interfaceID: Arrayish): Promise<boolean>;

  filters: {
    ConquestEntered(user: null, nConquests: null): EventFilter;

    OwnershipGranted(
      owner: string | null,
      previousTier: BigNumberish | null,
      newTier: BigNumberish | null
    ): EventFilter;
  };

  estimate: {
    assignOwnership(_address: string, _tier: BigNumberish): Promise<BigNumber>;

    conquestEntryID(): Promise<BigNumber>;

    conquestsEntered(arg0: string): Promise<BigNumber>;

    exitConquest(
      _user: string,
      _silverIds: BigNumberish[],
      _goldIds: BigNumberish[]
    ): Promise<BigNumber>;

    getOwnerTier(_owner: string): Promise<BigNumber>;

    goldCardFactory(): Promise<BigNumber>;

    isActiveConquest(arg0: string): Promise<BigNumber>;

    nextConquestTime(arg0: string): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: string,
      _from: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: Arrayish
    ): Promise<BigNumber>;

    onERC1155Received(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _amount: BigNumberish,
      _data: Arrayish
    ): Promise<BigNumber>;

    silverCardFactory(): Promise<BigNumber>;

    skyweaverAssets(): Promise<BigNumber>;

    supportsInterface(interfaceID: Arrayish): Promise<BigNumber>;
  };
}
