/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ConquestInterface extends ethers.utils.Interface {
  functions: {
    "assignOwnership(address,uint256)": FunctionFragment;
    "conquestEntryID()": FunctionFragment;
    "conquestsEntered(address)": FunctionFragment;
    "exitConquest(address,uint256[],uint256[])": FunctionFragment;
    "getOwnerTier(address)": FunctionFragment;
    "goldCardFactory()": FunctionFragment;
    "isActiveConquest(address)": FunctionFragment;
    "nextConquestTime(address)": FunctionFragment;
    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "silverCardFactory()": FunctionFragment;
    "skyweaverAssets()": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "assignOwnership",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "conquestEntryID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "conquestsEntered",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "exitConquest",
    values: [string, BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerTier",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "goldCardFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveConquest",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextConquestTime",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [string, string, BigNumberish[], BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "silverCardFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "skyweaverAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "assignOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conquestEntryID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conquestsEntered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exitConquest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "goldCardFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActiveConquest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextConquestTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "silverCardFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "skyweaverAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;

  events: {
    "ConquestEntered(address,uint256)": EventFragment;
    "OwnershipGranted(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ConquestEntered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipGranted"): EventFragment;
}

export class Conquest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ConquestInterface;

  functions: {
    assignOwnership(
      _address: string,
      _tier: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "assignOwnership(address,uint256)"(
      _address: string,
      _tier: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    conquestEntryID(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "conquestEntryID()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    conquestsEntered(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "conquestsEntered(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    exitConquest(
      _user: string,
      _silverIds: BigNumberish[],
      _goldIds: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "exitConquest(address,uint256[],uint256[])"(
      _user: string,
      _silverIds: BigNumberish[],
      _goldIds: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getOwnerTier(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getOwnerTier(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    goldCardFactory(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "goldCardFactory()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    isActiveConquest(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isActiveConquest(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    nextConquestTime(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "nextConquestTime(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    onERC1155BatchReceived(
      arg0: string,
      _from: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
      arg0: string,
      _from: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    onERC1155Received(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "onERC1155Received(address,address,uint256,uint256,bytes)"(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    silverCardFactory(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "silverCardFactory()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    skyweaverAssets(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "skyweaverAssets()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "supportsInterface(bytes4)"(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;
  };

  assignOwnership(
    _address: string,
    _tier: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "assignOwnership(address,uint256)"(
    _address: string,
    _tier: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  conquestEntryID(overrides?: CallOverrides): Promise<BigNumber>;

  "conquestEntryID()"(overrides?: CallOverrides): Promise<BigNumber>;

  conquestsEntered(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "conquestsEntered(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  exitConquest(
    _user: string,
    _silverIds: BigNumberish[],
    _goldIds: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "exitConquest(address,uint256[],uint256[])"(
    _user: string,
    _silverIds: BigNumberish[],
    _goldIds: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getOwnerTier(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  "getOwnerTier(address)"(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  goldCardFactory(overrides?: CallOverrides): Promise<string>;

  "goldCardFactory()"(overrides?: CallOverrides): Promise<string>;

  isActiveConquest(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "isActiveConquest(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  nextConquestTime(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "nextConquestTime(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  onERC1155BatchReceived(
    arg0: string,
    _from: string,
    _ids: BigNumberish[],
    _amounts: BigNumberish[],
    arg4: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
    arg0: string,
    _from: string,
    _ids: BigNumberish[],
    _amounts: BigNumberish[],
    arg4: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  onERC1155Received(
    _operator: string,
    _from: string,
    _id: BigNumberish,
    _amount: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "onERC1155Received(address,address,uint256,uint256,bytes)"(
    _operator: string,
    _from: string,
    _id: BigNumberish,
    _amount: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  silverCardFactory(overrides?: CallOverrides): Promise<string>;

  "silverCardFactory()"(overrides?: CallOverrides): Promise<string>;

  skyweaverAssets(overrides?: CallOverrides): Promise<string>;

  "skyweaverAssets()"(overrides?: CallOverrides): Promise<string>;

  supportsInterface(
    interfaceID: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "supportsInterface(bytes4)"(
    interfaceID: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    assignOwnership(
      _address: string,
      _tier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "assignOwnership(address,uint256)"(
      _address: string,
      _tier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    conquestEntryID(overrides?: CallOverrides): Promise<BigNumber>;

    "conquestEntryID()"(overrides?: CallOverrides): Promise<BigNumber>;

    conquestsEntered(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "conquestsEntered(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exitConquest(
      _user: string,
      _silverIds: BigNumberish[],
      _goldIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "exitConquest(address,uint256[],uint256[])"(
      _user: string,
      _silverIds: BigNumberish[],
      _goldIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    getOwnerTier(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getOwnerTier(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    goldCardFactory(overrides?: CallOverrides): Promise<string>;

    "goldCardFactory()"(overrides?: CallOverrides): Promise<string>;

    isActiveConquest(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "isActiveConquest(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    nextConquestTime(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "nextConquestTime(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: string,
      _from: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
      arg0: string,
      _from: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC1155Received(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC1155Received(address,address,uint256,uint256,bytes)"(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    silverCardFactory(overrides?: CallOverrides): Promise<string>;

    "silverCardFactory()"(overrides?: CallOverrides): Promise<string>;

    skyweaverAssets(overrides?: CallOverrides): Promise<string>;

    "skyweaverAssets()"(overrides?: CallOverrides): Promise<string>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "supportsInterface(bytes4)"(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    ConquestEntered(user: null, nConquests: null): EventFilter;

    OwnershipGranted(
      owner: string | null,
      previousTier: BigNumberish | null,
      newTier: BigNumberish | null
    ): EventFilter;
  };

  estimateGas: {
    assignOwnership(
      _address: string,
      _tier: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "assignOwnership(address,uint256)"(
      _address: string,
      _tier: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    conquestEntryID(overrides?: CallOverrides): Promise<BigNumber>;

    "conquestEntryID()"(overrides?: CallOverrides): Promise<BigNumber>;

    conquestsEntered(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "conquestsEntered(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exitConquest(
      _user: string,
      _silverIds: BigNumberish[],
      _goldIds: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "exitConquest(address,uint256[],uint256[])"(
      _user: string,
      _silverIds: BigNumberish[],
      _goldIds: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    getOwnerTier(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getOwnerTier(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    goldCardFactory(overrides?: CallOverrides): Promise<BigNumber>;

    "goldCardFactory()"(overrides?: CallOverrides): Promise<BigNumber>;

    isActiveConquest(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isActiveConquest(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextConquestTime(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "nextConquestTime(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: string,
      _from: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
      arg0: string,
      _from: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    onERC1155Received(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "onERC1155Received(address,address,uint256,uint256,bytes)"(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    silverCardFactory(overrides?: CallOverrides): Promise<BigNumber>;

    "silverCardFactory()"(overrides?: CallOverrides): Promise<BigNumber>;

    skyweaverAssets(overrides?: CallOverrides): Promise<BigNumber>;

    "skyweaverAssets()"(overrides?: CallOverrides): Promise<BigNumber>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportsInterface(bytes4)"(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    assignOwnership(
      _address: string,
      _tier: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "assignOwnership(address,uint256)"(
      _address: string,
      _tier: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    conquestEntryID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "conquestEntryID()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    conquestsEntered(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "conquestsEntered(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    exitConquest(
      _user: string,
      _silverIds: BigNumberish[],
      _goldIds: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "exitConquest(address,uint256[],uint256[])"(
      _user: string,
      _silverIds: BigNumberish[],
      _goldIds: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getOwnerTier(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getOwnerTier(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    goldCardFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "goldCardFactory()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isActiveConquest(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isActiveConquest(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextConquestTime(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "nextConquestTime(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onERC1155BatchReceived(
      arg0: string,
      _from: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
      arg0: string,
      _from: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "onERC1155Received(address,address,uint256,uint256,bytes)"(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    silverCardFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "silverCardFactory()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    skyweaverAssets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "skyweaverAssets()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "supportsInterface(bytes4)"(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
