/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface FreemintFactoryInterface extends Interface {
  functions: {
    assignOwnership: TypedFunctionDescription<{
      encode([_address, _tier]: [string, BigNumberish]): string;
    }>;

    batchMint: TypedFunctionDescription<{
      encode([_recipients, _ids, _amounts]: [
        string[],
        BigNumberish[],
        BigNumberish[]
      ]): string;
    }>;

    getOwnerTier: TypedFunctionDescription<{
      encode([_owner]: [string]): string;
    }>;

    getSkyweaverAssets: TypedFunctionDescription<{ encode([]: []): string }>;

    supportsInterface: TypedFunctionDescription<{
      encode([interfaceID]: [Arrayish]): string;
    }>;
  };

  events: {
    OwnershipGranted: TypedEventDescription<{
      encodeTopics([owner, previousTier, newTier]: [
        string | null,
        BigNumberish | null,
        BigNumberish | null
      ]): string[];
    }>;
  };
}

export class FreemintFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): FreemintFactory;
  attach(addressOrName: string): FreemintFactory;
  deployed(): Promise<FreemintFactory>;

  on(event: EventFilter | string, listener: Listener): FreemintFactory;
  once(event: EventFilter | string, listener: Listener): FreemintFactory;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): FreemintFactory;
  removeAllListeners(eventName: EventFilter | string): FreemintFactory;
  removeListener(eventName: any, listener: Listener): FreemintFactory;

  interface: FreemintFactoryInterface;

  functions: {
    assignOwnership(
      _address: string,
      _tier: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    batchMint(
      _recipients: string[],
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getOwnerTier(_owner: string): Promise<BigNumber>;

    getSkyweaverAssets(): Promise<string>;

    supportsInterface(interfaceID: Arrayish): Promise<boolean>;
  };

  assignOwnership(
    _address: string,
    _tier: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  batchMint(
    _recipients: string[],
    _ids: BigNumberish[],
    _amounts: BigNumberish[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  getOwnerTier(_owner: string): Promise<BigNumber>;

  getSkyweaverAssets(): Promise<string>;

  supportsInterface(interfaceID: Arrayish): Promise<boolean>;

  filters: {
    OwnershipGranted(
      owner: string | null,
      previousTier: BigNumberish | null,
      newTier: BigNumberish | null
    ): EventFilter;
  };

  estimate: {
    assignOwnership(_address: string, _tier: BigNumberish): Promise<BigNumber>;

    batchMint(
      _recipients: string[],
      _ids: BigNumberish[],
      _amounts: BigNumberish[]
    ): Promise<BigNumber>;

    getOwnerTier(_owner: string): Promise<BigNumber>;

    getSkyweaverAssets(): Promise<BigNumber>;

    supportsInterface(interfaceID: Arrayish): Promise<BigNumber>;
  };
}
