/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface OwnableMockInterface extends Interface {
  functions: {
    call_anyone: TypedFunctionDescription<{ encode([]: []): string }>;

    call_onlyOwner: TypedFunctionDescription<{ encode([]: []): string }>;

    call_throw: TypedFunctionDescription<{ encode([]: []): string }>;

    getOwner: TypedFunctionDescription<{ encode([]: []): string }>;

    transferOwnership: TypedFunctionDescription<{
      encode([_newOwner]: [string]): string;
    }>;
  };

  events: {
    OwnershipTransferred: TypedEventDescription<{
      encodeTopics([previousOwner, newOwner]: [
        string | null,
        string | null
      ]): string[];
    }>;
  };
}

export class OwnableMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): OwnableMock;
  attach(addressOrName: string): OwnableMock;
  deployed(): Promise<OwnableMock>;

  on(event: EventFilter | string, listener: Listener): OwnableMock;
  once(event: EventFilter | string, listener: Listener): OwnableMock;
  addListener(eventName: EventFilter | string, listener: Listener): OwnableMock;
  removeAllListeners(eventName: EventFilter | string): OwnableMock;
  removeListener(eventName: any, listener: Listener): OwnableMock;

  interface: OwnableMockInterface;

  functions: {
    call_anyone(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    call_onlyOwner(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    call_throw(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    getOwner(): Promise<string>;

    transferOwnership(
      _newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  call_anyone(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  call_onlyOwner(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  call_throw(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  getOwner(): Promise<string>;

  transferOwnership(
    _newOwner: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimate: {
    call_anyone(): Promise<BigNumber>;

    call_onlyOwner(): Promise<BigNumber>;

    call_throw(): Promise<BigNumber>;

    getOwner(): Promise<BigNumber>;

    transferOwnership(_newOwner: string): Promise<BigNumber>;
  };
}
