/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface OwnableMockInterface extends ethers.utils.Interface {
  functions: {
    "call_anyone()": FunctionFragment;
    "call_onlyOwner()": FunctionFragment;
    "call_throw()": FunctionFragment;
    "getOwner()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "call_anyone",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "call_onlyOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "call_throw",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "call_anyone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "call_onlyOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "call_throw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class OwnableMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: OwnableMockInterface;

  functions: {
    call_anyone(overrides?: Overrides): Promise<ContractTransaction>;

    "call_anyone()"(overrides?: Overrides): Promise<ContractTransaction>;

    call_onlyOwner(overrides?: Overrides): Promise<ContractTransaction>;

    "call_onlyOwner()"(overrides?: Overrides): Promise<ContractTransaction>;

    call_throw(overrides?: Overrides): Promise<ContractTransaction>;

    "call_throw()"(overrides?: Overrides): Promise<ContractTransaction>;

    getOwner(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getOwner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  call_anyone(overrides?: Overrides): Promise<ContractTransaction>;

  "call_anyone()"(overrides?: Overrides): Promise<ContractTransaction>;

  call_onlyOwner(overrides?: Overrides): Promise<ContractTransaction>;

  "call_onlyOwner()"(overrides?: Overrides): Promise<ContractTransaction>;

  call_throw(overrides?: Overrides): Promise<ContractTransaction>;

  "call_throw()"(overrides?: Overrides): Promise<ContractTransaction>;

  getOwner(overrides?: CallOverrides): Promise<string>;

  "getOwner()"(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    _newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    _newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    call_anyone(overrides?: CallOverrides): Promise<boolean>;

    "call_anyone()"(overrides?: CallOverrides): Promise<boolean>;

    call_onlyOwner(overrides?: CallOverrides): Promise<boolean>;

    "call_onlyOwner()"(overrides?: CallOverrides): Promise<boolean>;

    call_throw(overrides?: CallOverrides): Promise<boolean>;

    "call_throw()"(overrides?: CallOverrides): Promise<boolean>;

    getOwner(overrides?: CallOverrides): Promise<string>;

    "getOwner()"(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      _newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    call_anyone(overrides?: Overrides): Promise<BigNumber>;

    "call_anyone()"(overrides?: Overrides): Promise<BigNumber>;

    call_onlyOwner(overrides?: Overrides): Promise<BigNumber>;

    "call_onlyOwner()"(overrides?: Overrides): Promise<BigNumber>;

    call_throw(overrides?: Overrides): Promise<BigNumber>;

    "call_throw()"(overrides?: Overrides): Promise<BigNumber>;

    getOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "getOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    call_anyone(overrides?: Overrides): Promise<PopulatedTransaction>;

    "call_anyone()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    call_onlyOwner(overrides?: Overrides): Promise<PopulatedTransaction>;

    "call_onlyOwner()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    call_throw(overrides?: Overrides): Promise<PopulatedTransaction>;

    "call_throw()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    getOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
