/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TransactionOverrides } from ".";
import { OwnableMock } from "./OwnableMock";

export class OwnableMockFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _firstOwner: string,
    overrides?: TransactionOverrides
  ): Promise<OwnableMock> {
    return super.deploy(_firstOwner, overrides) as Promise<OwnableMock>;
  }
  getDeployTransaction(
    _firstOwner: string,
    overrides?: TransactionOverrides
  ): UnsignedTransaction {
    return super.getDeployTransaction(_firstOwner, overrides);
  }
  attach(address: string): OwnableMock {
    return super.attach(address) as OwnableMock;
  }
  connect(signer: Signer): OwnableMockFactory {
    return super.connect(signer) as OwnableMockFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OwnableMock {
    return new Contract(address, _abi, signerOrProvider) as OwnableMock;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_firstOwner",
        type: "address"
      }
    ],
    stateMutability: "nonpayable",
    type: "constructor"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address"
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address"
      }
    ],
    name: "OwnershipTransferred",
    type: "event"
  },
  {
    stateMutability: "nonpayable",
    type: "fallback"
  },
  {
    inputs: [],
    name: "call_anyone",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [],
    name: "call_onlyOwner",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [],
    name: "call_throw",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [],
    name: "getOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newOwner",
        type: "address"
      }
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161039f38038061039f83398101604081905261002f9161007e565b600080546001600160a01b0319166001600160a01b03831690811782556040518392907f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0908290a350506100ac565b60006020828403121561008f578081fd5b81516001600160a01b03811681146100a5578182fd5b9392505050565b6102e4806100bb6000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c806310f28194146100595780633fe9038014610077578063893d20e81461007f578063914cec9914610094578063f2fde38b1461009c575b005b6100616100af565b60405161006e91906101f7565b60405180910390f35b6100616100b4565b6100876100d7565b60405161006e91906101e3565b6100616100e6565b6100576100aa3660046101b5565b610117565b600190565b600060405162461bcd60e51b81526004016100ce9061024c565b60405180910390fd5b6000546001600160a01b031690565b600080546001600160a01b031633146101115760405162461bcd60e51b81526004016100ce90610268565b50600190565b6000546001600160a01b031633146101415760405162461bcd60e51b81526004016100ce90610268565b6001600160a01b0381166101675760405162461bcd60e51b81526004016100ce90610202565b600080546001600160a01b0319166001600160a01b0383811691821780845560405192939116917f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e09190a350565b6000602082840312156101c6578081fd5b81356001600160a01b03811681146101dc578182fd5b9392505050565b6001600160a01b0391909116815260200190565b901515815260200190565b6020808252602a908201527f4f776e61626c65237472616e736665724f776e6572736869703a20494e56414c60408201526949445f4144445245535360b01b606082015260800190565b6020808252600290820152613a2f60f01b604082015260600190565b60208082526026908201527f4f776e61626c65236f6e6c794f776e65723a2053454e4445525f49535f4e4f546040820152652fa7aba722a960d11b60608201526080019056fea2646970667358221220f829e0388df52508c02673b844c117b39b29877f28c3494e73b6d8162f08e21164736f6c63430006080033";
