/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface RewardFactoryInterface extends Interface {
  functions: {
    assignOwnership: TypedFunctionDescription<{
      encode([_address, _tier]: [string, BigNumberish]): string;
    }>;

    batchMint: TypedFunctionDescription<{
      encode([_to, _ids, _amounts, _data]: [
        string,
        BigNumberish[],
        BigNumberish[],
        Arrayish
      ]): string;
    }>;

    getAvailableSupply: TypedFunctionDescription<{ encode([]: []): string }>;

    getOwnerTier: TypedFunctionDescription<{
      encode([_owner]: [string]): string;
    }>;

    livePeriod: TypedFunctionDescription<{ encode([]: []): string }>;

    periodMintLimit: TypedFunctionDescription<{ encode([]: []): string }>;

    skyweaverAssets: TypedFunctionDescription<{ encode([]: []): string }>;

    supportsInterface: TypedFunctionDescription<{
      encode([interfaceID]: [Arrayish]): string;
    }>;

    updatePeriodMintLimit: TypedFunctionDescription<{
      encode([_newPeriodMintLimit]: [BigNumberish]): string;
    }>;
  };

  events: {
    OwnershipGranted: TypedEventDescription<{
      encodeTopics([owner, previousTier, newTier]: [
        string | null,
        BigNumberish | null,
        BigNumberish | null
      ]): string[];
    }>;

    PeriodMintLimitChanged: TypedEventDescription<{
      encodeTopics([oldMintingLimit, newMintingLimit]: [null, null]): string[];
    }>;
  };
}

export class RewardFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): RewardFactory;
  attach(addressOrName: string): RewardFactory;
  deployed(): Promise<RewardFactory>;

  on(event: EventFilter | string, listener: Listener): RewardFactory;
  once(event: EventFilter | string, listener: Listener): RewardFactory;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): RewardFactory;
  removeAllListeners(eventName: EventFilter | string): RewardFactory;
  removeListener(eventName: any, listener: Listener): RewardFactory;

  interface: RewardFactoryInterface;

  functions: {
    assignOwnership(
      _address: string,
      _tier: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    batchMint(
      _to: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      _data: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getAvailableSupply(): Promise<BigNumber>;

    getOwnerTier(_owner: string): Promise<BigNumber>;

    livePeriod(): Promise<BigNumber>;

    periodMintLimit(): Promise<BigNumber>;

    skyweaverAssets(): Promise<string>;

    supportsInterface(interfaceID: Arrayish): Promise<boolean>;

    updatePeriodMintLimit(
      _newPeriodMintLimit: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  assignOwnership(
    _address: string,
    _tier: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  batchMint(
    _to: string,
    _ids: BigNumberish[],
    _amounts: BigNumberish[],
    _data: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  getAvailableSupply(): Promise<BigNumber>;

  getOwnerTier(_owner: string): Promise<BigNumber>;

  livePeriod(): Promise<BigNumber>;

  periodMintLimit(): Promise<BigNumber>;

  skyweaverAssets(): Promise<string>;

  supportsInterface(interfaceID: Arrayish): Promise<boolean>;

  updatePeriodMintLimit(
    _newPeriodMintLimit: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    OwnershipGranted(
      owner: string | null,
      previousTier: BigNumberish | null,
      newTier: BigNumberish | null
    ): EventFilter;

    PeriodMintLimitChanged(
      oldMintingLimit: null,
      newMintingLimit: null
    ): EventFilter;
  };

  estimate: {
    assignOwnership(_address: string, _tier: BigNumberish): Promise<BigNumber>;

    batchMint(
      _to: string,
      _ids: BigNumberish[],
      _amounts: BigNumberish[],
      _data: Arrayish
    ): Promise<BigNumber>;

    getAvailableSupply(): Promise<BigNumber>;

    getOwnerTier(_owner: string): Promise<BigNumber>;

    livePeriod(): Promise<BigNumber>;

    periodMintLimit(): Promise<BigNumber>;

    skyweaverAssets(): Promise<BigNumber>;

    supportsInterface(interfaceID: Arrayish): Promise<BigNumber>;

    updatePeriodMintLimit(
      _newPeriodMintLimit: BigNumberish
    ): Promise<BigNumber>;
  };
}
